workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS debug
        script: |
          flutter build ios --debug
    artifacts:
      - build/ios/iphoneos/*.app
