name: Build iOS App

on:
  workflow_dispatch: # Elle başlatmak için

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0' 

    - name: Install dependencies
      run: flutter pub get

    - name: Enable iOS
      run: flutter config --enable-ios

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios && pod install && cd ..

    - name: Build iOS (debug)
      run: flutter build ios --debug

    # Eğer release IPA almak istiyorsan aşağıdakini kullanabilirsin:
    # - name: Build iOS (release)
    #   run: flutter build ipa --export-method ad-hoc

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build-output
        path: build/ios/iphoneos/
